#! /bin/bash

# libreria di appoggio
. ../installLib.sh

QUEUEMETRICS="/usr/local/queuemetrics/tomcat/webapps/queuemetrics"
FILESQL="$QUEUEMETRICS/WEB-INF/README/queuemetrics_sample.sql"
CPROPSQM="$QUEUEMETRICS/WEB-INF/configuration.properties"
FILEAST="$QUEUEMETRICS/WEB-INF/mysql-utils/extensions-examples/extensions_queuemetrics_18.conf"
FILEELA="/etc/asterisk/extensions_queuemetrics.conf"
FILEAPP="/etc/asterisk/extensions_custom.conf"


# Gestione AMI
FILEAMIQM="/etc/asterisk/manager_queuemetrics.conf"
FILEAMI="/etc/asterisk/manager_custom.conf"
AMIPASSWD=`< /dev/urandom tr -dc A-Z-a-z-0-9 | head -c${1:-15};echo;`
echo "" > $FILEAMIQM
echo "[qmmanager] ; generated by QM Espresso" >> $FILEAMIQM
echo "secret = $AMIPASSWD" >> $FILEAMIQM
echo "deny = 0.0.0.0/0.0.0.0" >> $FILEAMIQM
echo "permit= 127.0.0.1/255.255.255.0" >> $FILEAMIQM
echo "read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate" >> $FILEAMIQM
echo "write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate" >> $FILEAMIQM
echo "writetimeout = 5000" >> $FILEAMIQM

PWD=`pwd`

echo "FreePBX - Installing $0 from $PWD";
echo "File: $FILESQL"

/etc/init.d/qloaderd stop
/etc/init.d/queuemetrics stop



echo "" | mysql -uqueuemetrics -pjavadude queuemetrics

if [ $? -ge 1 ]; then

echo "Creating database"

mysql -uroot mysql <<"EOF"
  CREATE DATABASE IF NOT EXISTS queuemetrics;
  GRANT ALL PRIVILEGES ON queuemetrics.* TO 'queuemetrics'@'localhost' IDENTIFIED BY  'javadude';
EOF

mysql -uqueuemetrics -pjavadude queuemetrics < $FILESQL

fi

echo FreePBX config

FOUND="$(grep 'extensions_queuemetrics.conf' $FILEAPP)"
if [ -z "$FOUND" ]; then
    echo "#include extensions_queuemetrics.conf" >> $FILEAPP
fi

FOUND="$(grep 'manager_queuemetrics.conf' $FILEAMI)"
if [ -z "$FOUND" ]; then
    echo "#include manager_queuemetrics.conf" >> $FILEAMI
fi


cp $FILEAST $FILEELA

rext $FILEELA 11 7 'ChanSpy(${QM_AGENT_LOGEXT})'
rext $FILEELA 14 6 'ChanSpy(${QM_AGENT_LOGEXT})'

asterisk -rx "core reload"


echo QM config

rv $CPROPSQM callfile.dir tcp:qmmanager:${AMIPASSWD}@127.0.0.1

rv $CPROPSQM default.queue_log_file sql:P001
rv $CPROPSQM realtime.max_bytes_agent 65000
rv $CPROPSQM realtime.agent_button_1.enabled false
rv $CPROPSQM realtime.agent_button_2.enabled false
rv $CPROPSQM realtime.agent_button_3.enabled false
rv $CPROPSQM realtime.agent_button_4.enabled false

rv $CPROPSQM default.monitored_calls /var/spool/asterisk/monitor/
rv $CPROPSQM layout.logo http://www.loway.ch/images/logo_freepbx_200x72.png

rv $CPROPSQM realtime.members_only false
rv $CPROPSQM realtime.refresh_time 10
rv $CPROPSQM callfile.agentlogin.enabled false
rv $CPROPSQM callfile.agentlogoff.enabled false
rv $CPROPSQM callfile.transfercall.enabled true

rv $CPROPSQM default.rewriteLocalChannels true

rv $CPROPSQM default.hotdesking 86400
rv $CPROPSQM default.alwaysLogonUnpaused true
#rv $CPROPSQM default.autoconf.realtimeuri -

rv $CPROPSQM cluster.servers freepbx

rv $CPROPSQM default.crmapp "http://www.queuemetrics.com/sample_screen_pop.jsp?agent=[A]\&unique=[U]"

add $CPROPSQM cluster.freepbx.manager tcp:qmmanager:${AMIPASSWD}@127.0.0.1
add $CPROPSQM cluster.freepbx.queuelog sql:P001
add $CPROPSQM cluster.freepbx.monitored_calls /var/spool/asterisk/monitor/
add $CPROPSQM cluster.freepbx.callfile.dir tcp:qmmanager:${AMIPASSWD}@127.0.0.1

add $CPROPSQM realtime.useActivePolling true
add $CPROPSQM realtime.ajaxPollingDelay 5
add $CPROPSQM realtime.useRowCache true
add $CPROPSQM realtime.agent_autoopenurl true

sleep 5
killall -9  /usr/local/queuemetrics/java/bin/java

/etc/init.d/qloaderd start
/etc/init.d/queuemetrics start

allOK


